learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 显示所有主题
    url(r'^topics/$', views.topics, name='topics'),
    # 特定主题的详细内容
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 用于添加新主题
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于编辑主题
    url(r'^edit_topic/(?P<topic_id>\d+)$', views.edit_topic, name='edit_topic'),
    # 用于删除主题
    url(r'^delete_topic/(?P<topic_id>\d+)$', views.delete_topic, name='delete_topic'),
    # 用于添加新条目
    url(r'^new_entry/(?P<topic_id>\d+)$', views.new_entry, name='new_entry'),
    # 用于编辑已有条目
    url(r'^edit_entry/(?P<entry_id>\d+)$', views.edit_entry, name='edit_entry'),
    # 用于删除已有条目
    url(r'^delete_entry/(?P<entry_id>\d+)$', views.delete_entry, name='delete_entry'),

]

users/urls.py
"""定义users的URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    # 注销
    url(r'^logout/$', views.logout_views, name='logout'),
    # 注册
    url(r'^register/$', views.register, name='register')
]

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """主题下的不同条目"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(default='', blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.title+'\n'+self.text[:50] + '...' if len(self.text) > 50 else self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'text']
        labels = {'title': '标题', 'text': '笔记'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.shortcuts import render

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """学习笔记的主题页"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """单个主题的所有条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.user != topic.owner:
        return Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries, 'isError': 0}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """添加主题"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def edit_topic(request, topic_id):
    """编辑主题"""
    topic=Topic.objects.get(id=topic_id)
    if request.user != topic.owner:
        return Http404
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


@login_required
def delete_topic(request, topic_id):
    """删除主题"""
    topic=Topic.objects.get(id=topic_id)
    if request.user != topic.owner:
        return Http404
    if request.method == 'POST':
        topic.delete()
    return HttpResponseRedirect(reverse('learning_logs:topics'))



@login_required
def new_entry(request, topic_id):
    """为某一个主题添加条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.user != topic.owner:
        return Http404
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """修改特定条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.user != topic.owner:
        return Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'topic': topic, 'entry': entry, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """删除条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.user != topic.owner:
        return Http404
    if request.method == 'POST':
        entry.delete()
    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

users/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here

def logout_views(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """新用户注册"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>学习笔记</title>
	<link rel="shortcut icon" href="{% static 'img/learning_log.png' %}" />
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/layer/layer.js' %}"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript%}
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="#">学习笔记</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'learning_logs:index' %}">首页 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
           <a class="nav-link active" href="{% url 'learning_logs:topics' %}">主题</a>
          </li>
        </ul>
        <ul class="navbar navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li class="nav-item"><a>你好, {{ user.username }}</a></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'users:logout' %}">注销</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link active" href="{% url 'users:login' %}">登录</a></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'users:register' %}">注册</a></li>
        {% endif %}
    </ul>
    </div>

  </nav>
  <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

  </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>编辑笔记</h2>
{% endblock header %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>
    <p>编辑笔记：</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id%}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">保存更改</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>编辑主题</h2>
{% endblock header %}

{% block content %}
    <p>编辑主题：</p>
    <form action="{% url 'learning_logs:edit_topic' topic.id%}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">保存更改</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>记录你的学习</h1>
    </div>
{% endblock header %}

{% block content %}
    {% if not user.is_authenticated %}
    <h2>
        <a href="{% url 'users:register' %}">注册</a>一个账户，打造专属于你的学习笔记。
    </h2>
    {% endif %}
    <h2>学习笔记致力于记录你的学习轨迹，你可以用它来记录任何主题的内容。</h2>
    <h2>遇到新的学习主题？将它记录下来吧！</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>添加笔记</h2>
{% endblock header %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>
    <p>添加新的学习笔记：</p>
    <form action="{% url 'learning_logs:new_entry' topic.id%}" class="form" method="post" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">添加笔记</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>添加主题</h2>
{% endblock header %}

{% block content %}
    <p>添加新的主题：</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">添加主题</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% load datetime_filter %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p><a href="{% url 'learning_logs:new_entry' topic.id%}">添加笔记</a></p>

    {%for entry in entries%}
        <div class="card">
            <div class="card-header">
                <p><h3 style="float: left">{{ entry.title }}</h3><h4 style="float: right">{{ entry.date_added|time_filter }}</h4></p>
                <p style="clear: both">
                <small style="float: left"><a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑</a></small>
                <small style="float: left;margin-left: 10px;"><a onclick="delete_entry_query({id:'{{ entry.id }}'})" href="#">删除</a></small>
                <form style="display:none;" id="entry_delete_{{ entry.id }}"
                  action="{% url 'learning_logs:delete_entry' entry.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit"></button>
                </form>
                </p>
            </div>
            <div class="card-body">
                {{ entry.text |linebreaks}}
            </div>
        </div>
        {% empty %}
        该主题下暂时没有笔记。
    {% endfor %}

<script>
    function delete_entry_query(entry) {
         layer.open({
                title: '删除笔记',
                content: "确认删除该条笔记吗？",
                btn: ['确认', '取消'],
                yes: function(index) {
                    $('form#entry_delete_'+entry.id+' button').click();
                    layer.close(index);
                },
                btn2:function (index) {
                    layer.close(index);
                }
         })
    }
</script>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>主题</h2>
{% endblock header %}

{% block content %}
    <ul class="list-group list-group-flush" style="margin-left: -15px">
    {%for topic in topics%}
        <li class="list-group-item">
            <h3 style="float: left"><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
            <p style="float: right"><a onclick="delete_topic_query({ title:'{{ topic.text }}',id:'{{ topic.id }}' })" href="#">删除</a></p>
            <form style="display:none;" id="topic_delete_{{ topic.id }}"
                  action="{% url 'learning_logs:delete_topic' topic.id %}" method="POST">
                {% csrf_token %}
                <button type="submit"></button>
            </form>
            <script>
                function delete_topic_query(topic) {
                    layer.open({
                        title: topic.title,
                        content: "确认删除该主题吗？",
                        btn: ['确认', '取消'],
                        yes: function(index) {
                            $('form#topic_delete_'+topic.id+' button').click();
                            layer.close(index);
                        },
                        btn2:function (index) {
                            layer.close(index);
                        }
                    })
                }
            </script>
            <p style="float: right;margin-right: 20px;"><a href="{% url 'learning_logs:edit_topic' topic.id %}">编辑</a></p>
        </li>
        {% empty %}
        <li class="list-group-item">暂时没有学习主题。</li>
    {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}" style="margin: 10px 0"
       class="btn btn-primary btn-lg active" role="button" aria-pressed="true">添加主题</a>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>登录账户</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:login' %}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">登录</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>注册账户</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:register' %}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">注册</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}